spring.application.name=ms-proyectosserver.port=8082

# Configuración de Base de Datos Oracle
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:ORCL
spring.datasource.username=sistema
spring.datasource.password=sistema
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Configuración JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

# Logging
logging.level.root=INFO
logging.level.ms.example.ms_proyectos=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG